/* SPDX-License-Identifier: MIT
 *
 * genotp FFI — C bindings for the Rust `genotp` library.
 *
 * AUTO-GENERATED by cbindgen. Do NOT edit manually — regenerate by
 * running `cargo build -p genotp-ffi`. The source of truth is
 * `genotp-ffi/src/lib.rs`.
 *
 * Memory ownership rules:
 *   - Opaque handles (GenOtpHotp*, GenOtpTotp*, ...) are heap-allocated by
 *     constructors and MUST be freed exactly once via their *_free fn.
 *   - GenOtpString and GenOtpBytes returned by this library MUST be freed
 *     via genotp_string_free / genotp_bytes_free.
 *   - Strings are LENGTH-PREFIXED, **NOT null-terminated**.
 *       OK:   printf("%.*s", (int)s.len, s.data);
 *       UB:   printf("%s", s.data);
 *   - Empty results return data=NULL, len=0. Calling free on those is a no-op.
 *
 * Thread safety:
 *   - HOTP/TOTP/Verifier/Context/SkewDetector are safe to share across
 *     threads via `const` pointer (their methods take &self internally).
 *   - Do NOT call *_free concurrently with any other use of the same pointer.
 */

#ifndef GENOTP_H
#define GENOTP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Sentinel for "use current system time" in TOTP generate/verify.
 Using `u64::MAX` instead of `0` so `time = 0` (Unix epoch) remains a
 valid explicit timestamp.
 */
#define GENOTP_TIME_NOW UINT64_MAX

/*
 Error codes for the FFI surface.

 `#[repr(i32)]` to guarantee stable size across Rust / C platforms.
 Default `#[repr(C)]` for enum lets Rust pick the smallest int that
 fits, which can mismatch C's typical `int`-sized enum on the other
 side of the boundary.
 */
enum GenOtpErrorCode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    GenOtpErrorCode_Success = 0,
    GenOtpErrorCode_InvalidSecret = 1,
    GenOtpErrorCode_InvalidCode = 2,
    GenOtpErrorCode_InvalidDigits = 3,
    GenOtpErrorCode_InvalidAlgorithm = 4,
    GenOtpErrorCode_InvalidCounter = 5,
    GenOtpErrorCode_InvalidTime = 6,
    GenOtpErrorCode_VerificationFailed = 7,
    GenOtpErrorCode_RateLimited = 8,
    GenOtpErrorCode_ReplayAttack = 9,
    GenOtpErrorCode_NullPointer = 10,
    GenOtpErrorCode_InvalidUtf8 = 11,
    GenOtpErrorCode_AllocationFailed = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GenOtpErrorCode GenOtpErrorCode;
#else
typedef int32_t GenOtpErrorCode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GenOtpAlgorithm
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    GenOtpAlgorithm_Sha1 = 0,
    GenOtpAlgorithm_Sha256 = 1,
    GenOtpAlgorithm_Sha512 = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GenOtpAlgorithm GenOtpAlgorithm;
#else
typedef int32_t GenOtpAlgorithm;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 OTP type discriminator for [`OtpAuthUri`] / provisioning.
 */
enum GenOtpOtpType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    GenOtpOtpType_Hotp = 0,
    GenOtpOtpType_Totp = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GenOtpOtpType GenOtpOtpType;
#else
typedef int32_t GenOtpOtpType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 String result with explicit length. **NOT null-terminated.**

 `data = NULL, len = 0` is the canonical "empty" representation.
 Use `printf("%.*s", (int)s.len, s.data)` — never `printf("%s", ...)`.
 */
typedef struct {
    uint8_t *data;
    uintptr_t len;
} GenOtpString;

/*
 Byte array with explicit length.

 `data = NULL, len = 0` is the canonical "empty" representation.
 Always check `len > 0` before dereferencing `data`.
 */
typedef struct {
    uint8_t *data;
    uintptr_t len;
} GenOtpBytes;

typedef struct {
    uint8_t _private[0];
} GenOtpHotp;

typedef struct {
    uint8_t _private[0];
} GenOtpTotp;

typedef struct {
    uint8_t _private[0];
} GenOtpVerifier;

typedef struct {
    uint8_t _private[0];
} GenOtpContext;

typedef struct {
    uint8_t _private[0];
} GenOtpSkewDetector;

typedef struct {
    uint8_t _private[0];
} GenOtpOtpAuthUri;

typedef struct {
    uint8_t _private[0];
} GenOtpContextBuilder;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Library semver, null-terminated. Useful for runtime ABI compatibility
 check. C side sees this as `const uint8_t GENOTP_VERSION[6]`.
 */
extern const uint8_t GENOTP_VERSION[6];

void genotp_string_free(GenOtpString s);

void genotp_bytes_free(GenOtpBytes b);

void genotp_hotp_free(GenOtpHotp *hotp);

void genotp_totp_free(GenOtpTotp *totp);

void genotp_verifier_free(GenOtpVerifier *v);

void genotp_context_free(GenOtpContext *c);

void genotp_skew_detector_free(GenOtpSkewDetector *d);

void genotp_otpauth_uri_free(GenOtpOtpAuthUri *uri);

void genotp_context_builder_free(GenOtpContextBuilder *b);

GenOtpErrorCode genotp_generate_secret(uintptr_t bit_length, GenOtpBytes *out_bytes);

GenOtpErrorCode genotp_generate_default_secret(GenOtpBytes *out_bytes);

/*
 Stack-friendly RNG fill — writes to caller-provided buffer.
 No heap allocation. Suitable for embedded use.
 */
GenOtpErrorCode genotp_fill_secret(uint8_t *buf, uintptr_t buf_len);

GenOtpErrorCode genotp_base32_encode(const uint8_t *data,
                                     uintptr_t data_len,
                                     GenOtpString *out_string);

GenOtpErrorCode genotp_base32_decode(const char *data, GenOtpBytes *out_bytes);

GenOtpErrorCode genotp_hotp_new(const uint8_t *secret,
                                uintptr_t secret_len,
                                GenOtpAlgorithm algorithm,
                                uint32_t digits,
                                GenOtpHotp **out_hotp);

GenOtpErrorCode genotp_hotp_generate(const GenOtpHotp *hotp,
                                     uint64_t counter,
                                     GenOtpString *out_string);

GenOtpErrorCode genotp_hotp_verify(const GenOtpHotp *hotp,
                                   const char *code,
                                   uint64_t counter,
                                   bool *out_valid);

/*
 HOTP look-ahead resynchronization (RFC 4226 §7.4).

 `out_matched_counter` is set to the counter that matched, or 0 if no
 match (check `out_valid` first). Caller MUST update their stored counter
 to `matched + 1` after success to prevent replay.
 */
GenOtpErrorCode genotp_hotp_verify_with_resync(const GenOtpHotp *hotp,
                                               const char *code,
                                               uint64_t counter,
                                               uint64_t look_ahead,
                                               bool *out_valid,
                                               uint64_t *out_matched_counter);

GenOtpErrorCode genotp_totp_new(const uint8_t *secret,
                                uintptr_t secret_len,
                                GenOtpAlgorithm algorithm,
                                uint32_t digits,
                                uint64_t period,
                                GenOtpTotp **out_totp);

/*
 Generate TOTP code. Pass `time = GENOTP_TIME_NOW` (u64::MAX) for system time.
 */
GenOtpErrorCode genotp_totp_generate(const GenOtpTotp *totp,
                                     uint64_t time,
                                     GenOtpString *out_string);

/*
 Verify TOTP code. Pass `time = GENOTP_TIME_NOW` for system time.
 */
GenOtpErrorCode genotp_totp_verify(const GenOtpTotp *totp,
                                   const char *code,
                                   uint64_t time,
                                   uint64_t window,
                                   bool *out_valid);

/*
 Construct an OtpContext from raw bytes.
 */
GenOtpErrorCode genotp_context_from_bytes(const uint8_t *data,
                                          uintptr_t data_len,
                                          GenOtpContext **out_ctx);

GenOtpErrorCode genotp_context_empty(GenOtpContext **out_ctx);

/*
 Create a new context builder. Use the `_set_*` / `_set_custom` setters
 to add fields, then call [`genotp_context_builder_build`] to produce
 a canonicalized [`GenOtpContext`].

 Field values are serialized in sorted order with `\0` separators
 (alphabetical by key) so two builders with the same fields in
 different setter order produce byte-identical context — critical for
 binding determinism between issue-side and verify-side.

 Builder MUST be freed with [`genotp_context_builder_free`] even after
 `_build` is called.
 */
GenOtpErrorCode genotp_context_builder_new(GenOtpContextBuilder **out_builder);

/*
 Set the IP component. Recommend hashing the IP (e.g., SHA-256 hex)
 instead of the raw IP to avoid leaking it via error logs.
 */
GenOtpErrorCode genotp_context_builder_set_ip(GenOtpContextBuilder *b, const char *ip);

/*
 Set the device identifier (fingerprint hash, UUID, etc.).
 */
GenOtpErrorCode genotp_context_builder_set_device(GenOtpContextBuilder *b, const char *device);

/*
 Set the session token (stable across the login flow).
 */
GenOtpErrorCode genotp_context_builder_set_session(GenOtpContextBuilder *b, const char *session);

/*
 Set the origin URL (anti-phishing). Automatically normalized to
 `scheme://host[:port]` lowercase, with path/query/fragment stripped.
 */
GenOtpErrorCode genotp_context_builder_set_origin(GenOtpContextBuilder *b, const char *origin);

/*
 Set a custom field. Key is prefixed with `x-` internally to avoid
 collision with built-in fields in future versions.
 */
GenOtpErrorCode genotp_context_builder_set_custom(GenOtpContextBuilder *b,
                                                  const char *key,
                                                  const char *value);

/*
 Finalize the builder into a [`GenOtpContext`]. After this call, the
 builder is consumed — subsequent setter calls return `InvalidSecret`.
 The builder handle itself still MUST be freed with
 [`genotp_context_builder_free`].

 Output context is owned by the caller and must be freed via
 [`genotp_context_free`].
 */
GenOtpErrorCode genotp_context_builder_build(GenOtpContextBuilder *b, GenOtpContext **out_ctx);

/*
 Generate TOTP bound to context.
 */
GenOtpErrorCode genotp_totp_generate_bound(const GenOtpTotp *totp,
                                           const GenOtpContext *ctx,
                                           uint64_t time,
                                           GenOtpString *out_string);

/*
 Verify TOTP bound to context. Constant-time loop — does not early-return.
 */
GenOtpErrorCode genotp_totp_verify_bound(const GenOtpTotp *totp,
                                         const GenOtpContext *ctx,
                                         const char *code,
                                         uint64_t time,
                                         uint64_t window,
                                         bool *out_valid);

/*
 Generate HOTP bound to context.
 */
GenOtpErrorCode genotp_hotp_generate_bound(const GenOtpHotp *hotp,
                                           uint64_t counter,
                                           const GenOtpContext *ctx,
                                           GenOtpString *out_string);

/*
 Verify HOTP bound to context.
 */
GenOtpErrorCode genotp_hotp_verify_bound(const GenOtpHotp *hotp,
                                         const char *code,
                                         uint64_t counter,
                                         const GenOtpContext *ctx,
                                         bool *out_valid);

GenOtpErrorCode genotp_verifier_new(uint32_t max_attempts, GenOtpVerifier **out_verifier);

GenOtpErrorCode genotp_verifier_verify(const GenOtpVerifier *v,
                                       const char *code,
                                       const char *expected,
                                       bool *out_valid);

/*
 Verifier with context binding (Mode 2 — server-stored context check).
 */
GenOtpErrorCode genotp_verifier_verify_with_context(const GenOtpVerifier *v,
                                                    const char *code,
                                                    const char *expected,
                                                    const GenOtpContext *issued_ctx,
                                                    const GenOtpContext *request_ctx,
                                                    bool *out_valid);

GenOtpErrorCode genotp_verifier_is_rate_limited(const GenOtpVerifier *v, bool *out_rate_limited);

GenOtpErrorCode genotp_verifier_reset_attempts(const GenOtpVerifier *v);

GenOtpErrorCode genotp_skew_detector_new(uintptr_t capacity, GenOtpSkewDetector **out_detector);

GenOtpErrorCode genotp_skew_detector_enable_auto_adjust(const GenOtpSkewDetector *d);

GenOtpErrorCode genotp_skew_detector_current_offset(const GenOtpSkewDetector *d,
                                                    int64_t *out_offset);

/*
 Construct an OtpAuthUri builder for generating `otpauth://` URIs
 (suitable for QR code provisioning to Google Authenticator, Authy, etc.).

 `label` and `secret` are required. Secret should be Base32-encoded
 (use [`genotp_base32_encode`] to convert raw bytes). Padding `=` and
 whitespace in the secret are stripped automatically per Google Key
 URI Format spec.

 Use the `_set_*` setters to add optional fields, then call
 [`genotp_otpauth_uri_build`] to materialize the URI string.
 Free with [`genotp_otpauth_uri_free`].
 */
GenOtpErrorCode genotp_otpauth_uri_new(GenOtpOtpType otp_type,
                                       const char *label,
                                       const char *secret,
                                       GenOtpOtpAuthUri **out_uri);

/*
 Set the issuer (organization name shown in authenticator app).
 */
GenOtpErrorCode genotp_otpauth_uri_set_issuer(GenOtpOtpAuthUri *uri, const char *issuer);

/*
 Set the HMAC algorithm (default if unset: SHA1, matches Google
 Authenticator default).
 */
GenOtpErrorCode genotp_otpauth_uri_set_algorithm(GenOtpOtpAuthUri *uri, GenOtpAlgorithm algorithm);

/*
 Set the number of digits (6, 7, or 8). Default if unset: 6.
 */
GenOtpErrorCode genotp_otpauth_uri_set_digits(GenOtpOtpAuthUri *uri, uint32_t digits);

/*
 Set the TOTP period in seconds (only meaningful for TOTP).
 Default if unset: 30.
 */
GenOtpErrorCode genotp_otpauth_uri_set_period(GenOtpOtpAuthUri *uri, uint64_t period);

/*
 Set the HOTP counter (only meaningful for HOTP, required for HOTP
 per Google Key URI spec).
 */
GenOtpErrorCode genotp_otpauth_uri_set_counter(GenOtpOtpAuthUri *uri, uint64_t counter);

/*
 Build the final `otpauth://` URI string from the configured fields.
 Caller must free `out_string` with [`genotp_string_free`].

 The output is ready to be fed into a QR code library (e.g. `libqrencode`).
 Label, issuer, and secret are percent-encoded per RFC 3986 to handle
 special characters safely.
 */
GenOtpErrorCode genotp_otpauth_uri_build(const GenOtpOtpAuthUri *uri, GenOtpString *out_string);

/*
 Returns a static error message. Always succeeds unless `out_string` is NULL.
 */
GenOtpErrorCode genotp_error_message(GenOtpErrorCode error_code, GenOtpString *out_string);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GENOTP_H */
